//  ___FILEHEADER___
//  This file was generated by V.I.P.E.R Xcode Templates


import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController {
  // MARK: - Properties

  var presenter: ___VARIABLE_productName:identifier___PresenterInterface?
}

// MARK: - ___VARIABLE_productName:identifier___ViewInterface

extension ___VARIABLE_productName:identifier___ViewController: ___VARIABLE_productName:identifier___ViewInterface {}
