//  ___FILEHEADER___
//  This file was generated by V.I.P.E.R Xcode Templates


import UIKit

// MARK: - Presenter -> View

protocol ___VARIABLE_productName:identifier___ViewInterface: class {}

// MARK: - View -> Presenter

protocol ___VARIABLE_productName:identifier___PresenterInterface: class {}

// MARK: - Presenter -> Router

protocol ___VARIABLE_productName:identifier___RouterInterface: class {}

// MARK: - Presenter -> Interactor

protocol ___VARIABLE_productName:identifier___InteractorInterface: class {}
