//  ___FILEHEADER___
//  This file was generated by V.I.P.E.R Xcode Templates

import Foundation

class ___VARIABLE_productName:identifier___Interactor {
  // MARK: - Properties

  weak var presenter: ___VARIABLE_productName:identifier___PresenterInterface?
}

// MARK: - ___VARIABLE_productName:identifier___InteractorInterface

extension ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___InteractorInterface {}
